version: "3.9"

services:
  database:
    restart: always
    image: postgres:15.3-alpine3.18
    container_name: database
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    restart: always
    build: .
    container_name: server
    command: >
      sh -c "alembic upgrade head && poetry run uvicorn src.main:app --host 0.0.0.0 --port 8888 --reload"
    volumes:
      - .:/usr/src/app/
    ports:
      - "8888:8888"
    env_file:
      - ./.env
    depends_on:
      - database

volumes:
  db-data: