"""initial

Revision ID: 8d0d6e55801d
Revises:
Create Date: 2023-06-26 12:29:18.806443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8d0d6e55801d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employee", "first_name")
    op.drop_column("employee", "birth_year")
    op.drop_column("employee", "last_name")
    op.add_column(
        "employee_info", sa.Column("first_name", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "employee_info", sa.Column("last_name", sa.String(length=255), nullable=True)
    )
    op.add_column("employee_info", sa.Column("birth_year", sa.Integer(), nullable=True))
    op.add_column("employee_info", sa.Column("employee_id", sa.UUID(), nullable=True))
    op.drop_constraint(
        "employee_info_user_id_fkey", "employee_info", type_="foreignkey"
    )
    op.create_foreign_key(None, "employee_info", "employee", ["employee_id"], ["id"])
    op.drop_column("employee_info", "user_id")
    op.drop_column("employee_info", "social_media")
    op.drop_column("employee_info", "salary")
    op.drop_column("employee_info", "experience")
    op.drop_column("employee_info", "gitlab_link")
    op.add_column("position", sa.Column("base_salary", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("position", "base_salary")
    op.add_column(
        "employee_info",
        sa.Column(
            "gitlab_link", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "employee_info",
        sa.Column("experience", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "employee_info",
        sa.Column(
            "salary",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "employee_info",
        sa.Column(
            "social_media", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "employee_info",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "employee_info", type_="foreignkey")
    op.create_foreign_key(
        "employee_info_user_id_fkey", "employee_info", "employee", ["user_id"], ["id"]
    )
    op.drop_column("employee_info", "employee_id")
    op.drop_column("employee_info", "birth_year")
    op.drop_column("employee_info", "last_name")
    op.drop_column("employee_info", "first_name")
    op.add_column(
        "employee",
        sa.Column(
            "last_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "employee",
        sa.Column("birth_year", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "employee",
        sa.Column(
            "first_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
