"""initial

Revision ID: d4d65f6c2259
Revises:
Create Date: 2023-06-25 21:58:10.468058
"""
from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d4d65f6c2259"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("birth_year", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employee_email"), "employee", ["email"], unique=True)
    op.create_table(
        "position",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_position_id"), "position", ["id"], unique=False)
    op.create_table(
        "employee_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employment_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("social_media", sa.String(length=255), nullable=True),
        sa.Column("gitlab_link", sa.String(length=255), nullable=True),
        sa.Column("position_id", sa.Integer(), nullable=True),
        sa.Column("salary", sa.Float(), nullable=True),
        sa.Column("experience", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["position.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employee_info_id"), "employee_info", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employee_info_id"), table_name="employee_info")
    op.drop_table("employee_info")
    op.drop_index(op.f("ix_position_id"), table_name="position")
    op.drop_table("position")
    op.drop_index(op.f("ix_employee_email"), table_name="employee")
    op.drop_table("employee")
    # ### end Alembic commands ###
